project:
  type: website

website:
  title: "Dao of Sai"
  favicon: favicon.ico
  navbar:
    right:
      - blog.qmd
      - icon: github
        href: https://github.com/sai-prasanna
      - icon: bi-book
        href: https://scholar.google.com/citations?user=ZiB7SdEAAAAJ&hl=en
      - icon: twitter
        href: https://twitter.com/sai_prasanna
  site-url: saiprasanna.in
format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
execute:
  freeze: auto