---
categories:
- Algorithms
- Computer Science
- MOOC
date: 2016-04-02
layout: post
title: MIT OCW 6.006 Algorithms Course

---

MIT OCW course is one among the best introductory algorithm courses online. It introduces techniques  to analyse, and
understand how algorithms work.

[MIT OCW 6.006 Introduction to Algorithms Fall 2011](http://ocw.mit.edu/courses/electrical-engineering-and-computer-science/6-006-introduction-to-algorithms-fall-2011/) 
course is packed with awesome content. The open course ware website contains  video recording of the MIT course conducted at MIT and all the accompanying
notes, assignments, test content. It does not contain interactive content like udacity courses, but the content is in different
level.You need to know python to do this course's assignments. If you know how to code in any language , you can pick up basics of python in a day or two as it has simple syntax.

Prof. Erik Demaine ,Prof. Srinivas Devadas do a great job introducing concepts of algorithms and its analysis in the
main lectures. Victor Costan does exemplary job in recitation videos in explaining the concepts introduced by Erik and Srini
in easily understandable way. So don't miss out on recitation if you plan to look into this course.

The assignments are one of the fun parts of the whole course. They allow you to see how efficient algorithms can really make a difference in running time of your code. These guys have done a awesome job in designing each assignment in such a way that you can visualise the impact of algorithms. For example in assignment 3 where you are supposed to write code to detect crossings among wires, they have designed the assignment in such a way that you can see the result of your code running in the browser.

The course videos are also available in youtube as playlist. Checkout the first video.
<p>
<iframe width="560" height="315" src="https://www.youtube.com/embed/HtSuA80QTyo?list=PLUl4u3cNGP61Oq3tWYp6V_F-5jb5L2iHb" frameborder="0"> </iframe>
</p>

